### ISSUE TITLE
Fulfil Lightbend repo reqs

### ISSUE THREAD

**Issue by ktoso** [typesafehub/play-quota-scala#1]
Please add info about who maintains and if it's active etc in README

**Comment by gmethvin** [comment]
I wonder if we should move it to playframework? Since it's public it would be a good way to promote play-quota. This also needs to be added to our auto-update process when we release a new play version.

See also https://github.com/lightbend/play-quota-java

**Comment by ktoso** [comment]
+1 sounds like a good idea, it can live with playframework AFAICS, since not commercial

**Comment by ktoso** [comment]
We have similar things that we moved off from typesafehub to akka organisation a while ago btw, so... do it 👍

**Comment by gmethvin** [comment]
done!
